### PR TITLE
Site Module and master page redesign

### PR DESCRIPTION
**Pull request by JuviAndaya**
This request contains the page redesign for Site Module and Masterpage. This also includes the necessary css and js files.

### CODE REVIEW

**Comment by tlocke** [comment]
Hi @JuviAndaya it looks like the tests are failing?

**Comment by JuviAndaya** [comment]
Hi @tlocke , I added the fix for the test errors.

**Comment by tlocke** [comment]
Great, thanks I'll give it a try...

**Comment by JuviAndaya** [comment]
Hi @tlocke I updated the js files. it seems the js are not working. Fixed and tested it.

**Pull request closed without merging**
